#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : layer-shell-qt
Version  : 6.0.5
Release  : 50
URL      : https://download.kde.org/stable/plasma/6.0.5/layer-shell-qt-6.0.5.tar.xz
Source0  : https://download.kde.org/stable/plasma/6.0.5/layer-shell-qt-6.0.5.tar.xz
Source1  : https://download.kde.org/stable/plasma/6.0.5/layer-shell-qt-6.0.5.tar.xz.sig
Source2  : D7574483BB57B18D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 LGPL-3.0 MIT
Requires: layer-shell-qt-lib = %{version}-%{release}
Requires: layer-shell-qt-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(wayland-client)
BuildRequires : extra-cmake-modules wayland
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : pkg-config
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : qt6base-dev
BuildRequires : qt6wayland-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-staticdev
BuildRequires : wayland-protocols-dev plasma-wayland-protocols-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
SPDX-License-Identifier: CC0-1.0

%package dev
Summary: dev components for the layer-shell-qt package.
Group: Development
Requires: layer-shell-qt-lib = %{version}-%{release}
Provides: layer-shell-qt-devel = %{version}-%{release}
Requires: layer-shell-qt = %{version}-%{release}

%description dev
dev components for the layer-shell-qt package.


%package lib
Summary: lib components for the layer-shell-qt package.
Group: Libraries
Requires: layer-shell-qt-license = %{version}-%{release}

%description lib
lib components for the layer-shell-qt package.


%package license
Summary: license components for the layer-shell-qt package.
Group: Default

%description license
license components for the layer-shell-qt package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) D7574483BB57B18D' gpg.status
%setup -q -n layer-shell-qt-6.0.5
cd %{_builddir}/layer-shell-qt-6.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716386142
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716386142
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/layer-shell-qt
cp %{_builddir}/layer-shell-qt-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/layer-shell-qt/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe || :
cp %{_builddir}/layer-shell-qt-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/layer-shell-qt/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/layer-shell-qt-%{version}/LICENSES/LGPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/layer-shell-qt/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
cp %{_builddir}/layer-shell-qt-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/layer-shell-qt/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
cp %{_builddir}/layer-shell-qt-%{version}/README.md.license %{buildroot}/usr/share/package-licenses/layer-shell-qt/2b8a08519120d2d6798194c1ee82c17af8f3b45d || :
cp %{_builddir}/layer-shell-qt-%{version}/src/layer-shell.json.license %{buildroot}/usr/share/package-licenses/layer-shell-qt/2b8a08519120d2d6798194c1ee82c17af8f3b45d || :
cp %{_builddir}/layer-shell-qt-%{version}/src/wlr-layer-shell-unstable-v1.xml.license %{buildroot}/usr/share/package-licenses/layer-shell-qt/6653c5e493b925062b55673ef831a181dddb7dc7 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/LayerShellQt/Shell
/usr/include/LayerShellQt/Window
/usr/include/LayerShellQt/layershellqt_export.h
/usr/include/LayerShellQt/shell.h
/usr/include/LayerShellQt/window.h
/usr/lib64/cmake/LayerShellQt/LayerShellQtConfig.cmake
/usr/lib64/cmake/LayerShellQt/LayerShellQtConfigVersion.cmake
/usr/lib64/cmake/LayerShellQt/LayerShellQtTargets-relwithdebinfo.cmake
/usr/lib64/cmake/LayerShellQt/LayerShellQtTargets.cmake
/usr/lib64/libLayerShellQtInterface.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libLayerShellQtInterface.so.6.0.5
/V3/usr/lib64/qt6/plugins/wayland-shell-integration/liblayer-shell.so
/V3/usr/lib64/qt6/qml/org/kde/layershell/libLayerShellQtQml.so
/usr/lib64/libLayerShellQtInterface.so.6
/usr/lib64/libLayerShellQtInterface.so.6.0.5
/usr/lib64/qt6/plugins/wayland-shell-integration/liblayer-shell.so
/usr/lib64/qt6/qml/org/kde/layershell/LayerShellQtQml.qmltypes
/usr/lib64/qt6/qml/org/kde/layershell/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/layershell/libLayerShellQtQml.so
/usr/lib64/qt6/qml/org/kde/layershell/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/layer-shell-qt/2b8a08519120d2d6798194c1ee82c17af8f3b45d
/usr/share/package-licenses/layer-shell-qt/6653c5e493b925062b55673ef831a181dddb7dc7
/usr/share/package-licenses/layer-shell-qt/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/layer-shell-qt/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
/usr/share/package-licenses/layer-shell-qt/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/layer-shell-qt/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe
